### ISSUE TITLE
Feature: When cookies are provided in the request, ensure preview content is returned

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-api#10]
It's important that logged in users can get draft and preview content so they can work on drafted posts.

**Comment by rsm0128** [comment]
@drewbaker request is sent from server side and user's cookie is not there. We might need to use token based authentication for it.
In this [PR](https://github.com/funkhaus/fuxt-api/pull/69), I made preview work for the requests with some reserved params.
As you know, preview link on WP admin page is something like this `/hello-world/?id=1&type=post&status=draft&preview=true&slug=hello-world&uri=/hello-world/`. On frontend part the params will be sent via REST api and `fuxt-api` parses the request and send draft post data.

Here is the frontend code update example.
https://github.com/funkhaus/see-me-frontend/pull/10/files

Please let me know your opinion.

**Comment by drewbaker** [comment]
If the user is logged into Wordpress, they have the cookie. This worked fine with WP GQL so not sure why it has to be different here.

I suspect with see me it’s just that the site is on a different domain (Netlify). When we move Wordpress to a sub domain of main site I think the cookies will work.

**Comment by rsm0128** [comment]
Please check this PR.
[https://github.com/funkhaus/fuxt-api/pull/70](https://github.com/funkhaus/fuxt-api/pull/69)

FYI, WP REST API engine set current user as guest at the beginning of the request handler and so user related functions such as `is_user_logged_in` and `wp_get_current_user` doesn't work. So I used `determine_current_user` hook to determine user id by cookie data.

**Comment by drewbaker** [comment]
Closed with https://github.com/funkhaus/fuxt-api/pull/70
