### ISSUE TITLE
Provide better documentation for the API inspectors

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-api#17]
We should aim to have the `fuxt` endpoints documented to this level:

![Screenshot 2024-09-26 at 6 01 12 PM](https://github.com/user-attachments/assets/74039711-32be-4b57-b742-95f1d36a5f68)

**Comment by drewbaker** [comment]
Really want toe inspector to show _fields, response examples etc.

**Comment by rsm0128** [comment]
@drewbaker Have you had chance to check this PR? https://github.com/funkhaus/fuxt-api/pull/34
It has the Response Example. Please check and let me know if you have any questions.
![image](https://github.com/user-attachments/assets/0351d335-aa68-4ef5-a8a3-4d536be45cd5)
![image](https://github.com/user-attachments/assets/c961e221-b54a-4586-9402-20fd1557c4df)

**Comment by drewbaker** [comment]
Totally missed that PR, thanks for the reminder! I just merged it.
