### ISSUE TITLE
Queries with multiple params only returns the last query param

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/fuxt-api#36]
Seeing an issue where this query `{site}.com/wp-json/fuxt/v1/post?uri=artists&fields=terms&fields=children` only returns the artists page children and not children tags (as in terms). 

If i rephrase it as `{site}.com/wp-json/fuxt/v1/post?uri=artists&fields=children&fields=terms` then it only returns artists page tags and not children. 
 
Queries should return all params (eg terms and children), not just the last param.

**Comment by rsm0128** [comment]
@dChiamp `fields=terms&fields=children` is the same with `fields=children`.
You can use `fields[]=terms&fields[]=children` or `fields=terms,children`

**Comment by drewbaker** [comment]
@rsm0128 that URL is built in Nuxt, I think they use `ufo` to do it https://github.com/unjs/ufo

```
const { data, status, error, refresh } = await useFetch('/api/modules', {
  query: { 
      uri: '/artists/', 
      fields: ['children', 'terms']
  }
})
```

We need to support the URL that that generates, as that is the "reactive" way to build out queries in Nuxt.

**Comment by rsm0128** [comment]
PHP doesn't support multiple params in url. This [PR](https://github.com/funkhaus/fuxt-api/pull/37) solves the problem for fuxt/v1/ rest api endpoint
