### ISSUE TITLE
Bug: Menu endpoint by name stopped working

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-api#38]
`https://see-me-api.flywheelsites.com/wp-json/fuxt/v1/menus?name=Main%20Menu`

![Screenshot 2024-10-11 at 10 57 56 AM](https://github.com/user-attachments/assets/ee50dc94-727f-4ec9-b2c5-2e76d2ff4bef)
![Screenshot 2024-10-11 at 10 57 43 AM](https://github.com/user-attachments/assets/ba8ecad4-4eca-4fb5-a52b-832e0b092666)

**Comment by drewbaker** [comment]
OK so the problem is that the encoded params become `Main%20Menu` and WordPress doesn't handle the decoding on those params now.

So in `class-rest-menu-controller.php` I added a `urldecode()` around the menu name param.

![Screenshot 2024-10-11 at 11 07 08 AM](https://github.com/user-attachments/assets/a61e950b-4560-408a-94a0-032fe659e5e0)

@rsm0128 I suspect you will need to do this for all params now.

**Comment by rsm0128** [comment]
@drewbaker I fixed the issue in this commit https://github.com/funkhaus/fuxt-api/commit/81b7899296fe2a967737557a2d032c018b5ec246
