### ISSUE TITLE
Unable to query for Post by URI

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/fuxt-api#47]
Currently it seems there is no way to query for a specific ("news") post by 'uri' eg `/news/post-2/`

I'd expect something like posts with 'uri' param or post with type "post" eg `/post?uri=/news/post-2/&type=post` to work.

**Comment by drewbaker** [comment]
Are you sure that’s the URI in WordPress? I would have thought it would have the ID in the URL?

**Comment by rsm0128** [comment]
@dChiamp We use `get_page_by_path()` WP core function to get post object from URI. I checked the function and found that the function doesn't work if we have custom base in URL structure.
![image](https://github.com/user-attachments/assets/021c8564-184d-49e1-a110-6cd4b5c23b31)
So we can exclude the base url from the query.
Or if it's required, let me try to implement the feature to handle the custom URL structure.

**Comment by drewbaker** [comment]
We should make it work with the custom structure for sure. The person making the API request might not know about the custom base.
