### ISSUE TITLE
Clean up `caption` and `citation` fields to not have parent HTML tags

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-api#62]
For the `gallery` and `quote` blocks, the caption and citation fields contain a bunch of junk HTML tags.

![Screenshot 2024-10-31 at 2 12 24 PM](https://github.com/user-attachments/assets/ed5f2eb6-1f9c-4a5c-97d6-07029f1d3a05)

It's probably a good idea to avoid specific block logic I think. So perhaps we look at fields like `citation` and `caption` and handle those?

NOTE: A caption or citation can contain HTML tags, like strong or link tags. So we can't just strip_tags() on it.

**Comment by drewbaker** [comment]
NOTE: The core embed blocks also have captions.

**Comment by drewbaker** [comment]
Thinking about this some more, I think we the "last child" will always be the caption, if it's present.

**Comment by dChiamp** [comment]
Hey added the most recent updates and citation is working well, but still seeing an issue with captions:
<img width="1275" alt="captions" src="https://github.com/user-attachments/assets/5933c4a5-8ef7-423c-8db7-279646308564">
