### ISSUE TITLE
/posts orderby menu_order

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/fuxt-api#80]
Hey @rsm0128, while working on a See Me change order I just noticed an unexpected result from the `/posts` endpoint: the `orderby` field default is `date` with no option to set as 'menu_order'. This is resulting in an undesired grid layout.
` order: asc` vs desc works as expected. 

Can you please update the `orderby` field to include `menu_order` or equivalent option to set results as the actual page order?
This is one is "hi priority" as it's the last update to this site and would love to be done with it by end of day / year tomorrow if possible.

Thanks!

**Comment by rsm0128** [comment]
For blog post, the default orderby is `date`. But for the other post types, it's `menu_order` by default. Anyway, let me check in more detail
