### ISSUE TITLE
Issue fetching grandchildren!

### ISSUE THREAD

**Issue by Sveb** [funkhaus/fuxt-api#83]
The issue I'm facing is the folowing.
This is my query:
![Screenshot 2024-12-19 at 19 12 36](https://github.com/user-attachments/assets/f5ff4286-13bc-49b8-8cc4-4bfde37b6533)

This is my backend:
![Screenshot 2024-12-19 at 19 11 59](https://github.com/user-attachments/assets/b5ce335a-de8d-4c3f-919b-88d20bde6b49)

This is what is getting returned:
![Screenshot 2024-12-19 at 19 11 39](https://github.com/user-attachments/assets/ba5fea0e-a8ff-43b0-8768-d53f1e432dcf)

I was expecting to have all / 100 per page of the children (directors), but I'm only getting one per parent (director-category).

How do I query for all the grandchildren?

**Comment by rsm0128** [comment]
@Sveb Could you let me know the site name you are experiencing the problem, please? It will make me easier to find the reasons

**Comment by Sveb** [comment]
> @Sveb Could you let me know the site name you are experiencing the problem, please? It will make me easier to find the reasons

Yes of course, my bad.

The site is [DressCode](https://dress-code-api.flywheelsites.com/wp-admin/admin.php?page=nestedpages)

**Comment by rsm0128** [comment]
@Sveb We had set the grand child limit as 1 intentionally because most of cases only 1 grand child is required.
I created a PR. Please check and let me know
https://github.com/funkhaus/fuxt-api/pull/84

**Comment by drewbaker** [comment]
I merged it. So how would Svebor use this new field?
